name: Dersu
description: Your assistant in the mountain
url: https://dersu.uz
timezone: Europe/Madrid
permalink: pretty
highlighter: rouge

# Future multilingual support:
# https://www.kooslooijesteijn.net/blog/multilingual-website-with-jekyll-collections
# https://talk.jekyllrb.com/t/making-a-multilingual-website-with-collections/4824/2
